### ISSUE TITLE
oni need the user home path with no Non-ASCII characters.

### ISSUE THREAD

**Issue by QijianZhang** [onivim/oni#808] opened 2017-10-19 04:47 UTC
This problem I have encountered several times with some applications. The oni work well, I mean it's window, menu have no problem, but the **Editor shows nothing but just black**. So it should be the neovim's problem.

**Comment by CrossR** [comment] 2017-10-19 09:57
Usually when a fully black screen is shown, neovim is showing an error, but since this error doesn't have a nice way of externalising it, Oni can only show a black screen.

Hitting the enter key a few time may dismiss the error, in which case you can use the `:messages` command to view what errors were encountered on startup. I've had similar issues when my `init.vim` has had errors in it due to plugins.

In this case, it sounds like neovim is failing to open the file due to some certain files, which could either be how oni is passing those files, or neovim itself. Then neovim is attempting to show said error, and failing as there is currently no way to view this error, until you are into Oni and use the messages command.

**Comment by QijianZhang** [comment] 2017-10-19 14:22
I found the nvim.exe and ran it, it showed error in the cmd. It said it can't create certain file. This file path should located in my home page (on Windows) , but it's not the user's name, but messy code. So I knew it must be the reason that file path contains Non-ASCII chars. And when I installed it with another Windows account whose user's name contains no Non-ASCII, it did worked well.

**Comment by bryphe** [comment] 2017-10-21 00:34
Hi @QijianZhang , would it be possible to share the file path that is causing issues? If it's an issue that repros with `nvim.exe` as well, it might be worth logging at the core Neovim tracker as well: https://github.com/neovim/neovim/issues (and it's possible there may already be an issue tracking it).

In any case, it would be helpful to have an exact set of reproduction steps to isolate this. Thank you!

**Comment by QijianZhang** [comment] 2017-10-21 11:18
I think nvim doesn't support the local charset(Chinese on Windows). My Windows account name is in Chinese, and I have encountered similar problems before. So I decided to change my account name. After that, I installed oni again, it did work. But I didn't keep that error message. I think nvim doesn't understand the Chinese characters, and when it wants to create needed files in the user home dir, it gives the wrong file path.

**Comment by CrossR** [comment] 2018-06-21 14:51
I've done a bit of basic testing and it seemed to work for me now for a user with Chinese in their name.

That plus the improvements so we don't just blank the screen on errors now should have sorted this, so I'll close this. If someone else runs into it with a reproducible case, might be easier to sort for us/nvim-core.

**Closed by CrossR** 2018-06-21 14:51 UTC
Labels: bug, needs-disambiguation, neovim-core
