### ISSUE TITLE
Doesn't work on windows 10 32bit

### ISSUE THREAD

**Issue by paperbenni** [onivim/oni#1780] opened 2018-03-12 18:58 UTC
Hello, I'm having a problem with running OniVim on my 2 in 1 windows tablet running windows 10 32 bit, some shitty intel atom thingy and 2gb ram. On the releases page it sais that it's windows 32bit which seems to be true for the electron ui but not for neovim itself. OnVIm just opens up showing the title bar and the rest of the window is gray. I went into the program folder and tried to open the bundled version and it showed the error message that normally occurs when you try to open a 64 bit program on a 32bit machine. Has anyone even tested onivim on win32 since x86 on windows is basically dead, even on laptops? Would be nice if you could fix that.

**Comment by CrossR** [comment] 2018-03-12 19:13
The error you are getting would make sense, it looks like over in the releases downloader, there is the following code : 
```
            "win32": {
                "name": "nvim-win64.zip"
            },
```
https://github.com/onivim/oni-neovim-binaries/blob/daa5cc2a400f45eb5dea014ebca2b155cc0a22b6/lib/postinstall.js#L38-L40

Which suggests we are downloading the 64 bit binaries regardless.
And when we build electron we build with the `--arch ia32` flag and I'm assuming that means 32 bit electron install.

It may just be as simple as splitting that up to use the correct binary.

**Comment by CrossR** [comment] 2018-03-23 00:00
Just an update on this, I reproduced it on a 32bit VM.
Swapping out the Neovim binaries manually to the 32 bit ones worked, so it looks like that is all we have to change.

I'll look at adding that now.

**Comment by CrossR** [comment] 2018-03-29 10:43
This ended up being a little more involved than it looked, since we needed to fix the neovim binary, the ripgrep (used for searching) binary, update the release downloader to deal with that and then update the build steps of the project to deal with those 3 changes...

That said, its pretty much done now so hopefully the next release will have a 32bit build!
Just doing some final bits of testing and fixing up the build steps.

**Comment by CrossR** [comment] 2018-04-03 09:49
Sorry for the delay! There is a 32bit version in the release candidate here : https://github.com/onivim/oni/releases

That should be going fully live soon.

**Comment by CrossR** [comment] 2018-06-21 15:22
Ooops, this should have been closed out once the 32bit version was released.

Closing now.

**Closed by CrossR** 2018-06-21 15:22 UTC
