### ISSUE TITLE
Suggestion list in command line popup doesn't do anything

### ISSUE THREAD

**Issue by rgehan** [onivim/oni#1763] opened 2018-03-09 13:45 UTC
**How to reproduce**:
- Type (in normal mode) `:e`
- Press `Tab` => a list of suggestions appears
- Try to click one of this suggestion item, or to move to it with the arrow keys

**What happens**:
Nothing, the item is not selected. Even worse, in the case of the click, it clicks behind the popup (in my example, into the file explorer, opening a file as a result)

When pressing tab, it also seems to print `....` at the location the command line input would be on a terminal Vim.

**Recording**:
![](http://g.recordit.co/c3cQyQldqc.gif)

**Comment by Akin909** [comment] 2018-03-09 15:55
@rgehan the `wildmenu` is actually controlled by vim and not oni really so to navigate through it you have to use vims `wildchar` this is by default set to `<TAB>` to choose a selection you hit `Enter` these can be configured in your `init.vim` regarding the dots see #1728 and #1292 it is an artifact caused by neovim which should be fixed soon.

Because the pain just mirrows neovim events we can't as far as I believe add things like on click etc. as the menu is simply a way or visualising what vim's `wildmenu` is doing

**Comment by rgehan** [comment] 2018-03-09 16:10
It makes more sense then. Thanks, I didn't know about these shortcuts.
I'll close the issue.

**Comment by Akin909** [comment] 2018-03-09 17:00
I'll add the info above to the documentation to make it clearer

**Closed** 2018-03-10 22:32 UTC
