### ISSUE TITLE
Uh oh! Unable to launch Neovim...

### ISSUE THREAD

**Issue by Beyarz** [onivim/oni#2662] opened 2018-11-02 12:56 UTC
**Oni Version:**
0.3.6

**Neovim Version (Linux only):**
0.3.1

**Operating System:**
macOS Mojave

**Issue:**
I received this error when opening Oni
> Uh oh! Unable to launch Neovim...
> Neovim v0.2.1 is required to run Oni.

**Expected behavior:**
To run properly.

**Actual behavior:**
Unable to launch Neovim.

**Steps to reproduce:**
Open the app, that's really it.

**Comment by Beyarz** [comment] 2018-11-02 12:58
Oh, this issue looks to be a dupe of [#2354](https://github.com/onivim/oni/issues/2354)

**Comment by Beyarz** [comment] 2018-11-02 13:02
Reinstalling doesn't help either.

**Comment by CrossR** [comment] 2018-11-03 11:50
Yep, this looks to be the same as the issue linked over in #2354 or #2396.

I'll close this out for now since we have a discussion on going, but we aren't fully sure of the cause.

**Closed by CrossR** 2018-11-03 11:50 UTC
