### ISSUE TITLE
Oni freezes after inserting the 1st character

### ISSUE THREAD

**Issue by muream** [onivim/oni#1076] opened 2017-12-05 18:28 UTC
Hey there, 
I just installed oni from the AUR on Arch, no configuration done whatsoever and the editor freezes as soon as I insert the 1st character.
The tabline and line numbers also appear after inserting the character and no colorscheme seems to be loaded.
As soon as the character is entered I get two warnings and an error in the console:

```
bundle.js:1 Unhandled command: mode_info_set
t.warn @ bundle.js:1
t.forEach @ bundle.js:44
_handleNotification @ bundle.js:44
_neovim.on @ bundle.js:44
emitTwo @ events.js:125
emit @ events.js:213
_decoder.on @ bundle.js:26
emitOne @ events.js:115
emit @ events.js:210
addChunk @ _stream_readable.js:252
readableAddChunk @ _stream_readable.js:239
Readable.push @ _stream_readable.js:197
Transform.push @ _stream_transform.js:147
n.push @ bundle.js:44
flush @ bundle.js:5
o._transform @ bundle.js:44
Transform._read @ _stream_transform.js:186
Transform._write @ _stream_transform.js:174
doWrite @ _stream_writable.js:371
writeOrBuffer @ _stream_writable.js:357
Writable.write @ _stream_writable.js:274
ondata @ _stream_readable.js:628
emitOne @ events.js:115
emit @ events.js:210
addChunk @ _stream_readable.js:252
readableAddChunk @ _stream_readable.js:239
Readable.push @ _stream_readable.js:197
onread @ net.js:589
```
```
bundle.js:1 Unhandled command: mode_info_set
t.warn	@	bundle.js:1
t.forEach	@	bundle.js:44
_handleNotification	@	bundle.js:44
_neovim.on	@	bundle.js:44
emitTwo	@	events.js:125
emit	@	events.js:213
_decoder.on	@	bundle.js:26
emitOne	@	events.js:115
emit	@	events.js:210
addChunk	@	_stream_readable.js:252
readableAddChunk	@	_stream_readable.js:239
Readable.push	@	_stream_readable.js:197
Transform.push	@	_stream_transform.js:147
n.push	@	bundle.js:44
flush	@	bundle.js:5
o._transform	@	bundle.js:44
Transform._read	@	_stream_transform.js:186
Transform._write	@	_stream_transform.js:174
doWrite	@	_stream_writable.js:371
writeOrBuffer	@	_stream_writable.js:357
Writable.write	@	_stream_writable.js:274
ondata	@	_stream_readable.js:628
emitOne	@	events.js:115
emit	@	events.js:210
addChunk	@	_stream_readable.js:252
readableAddChunk	@	_stream_readable.js:239
Readable.push	@	_stream_readable.js:197
onread	@	net.js:589
```
```
bundle.js:1 Uncaught TypeError: Cannot read property 'line' of undefined
    at l._onBufferUpdate (bundle.js:44)
    at EventEmitter.d._editor.onBufferChanged.subscribe (bundle.js:44)
    at emitOne (events.js:120)
    at EventEmitter.emit (events.js:210)
    at t.Event.dispatch (bundle.js:1)
    at R.notifyBufferChanged (bundle.js:44)
    at t.R.s.subscribe [as _next] (bundle.js:44)
    at t.__tryOrUnsub (bundle.js:1)
    at t.next (bundle.js:1)
    at t._next (bundle.js:1)
```

If you need any other information or want me to try something, please ask away!
Thanks.

**Comment by bryphe** [comment] 2017-12-05 19:56
Hi @muream , thanks for trying Oni! Sorry you hit this on the first launch - appreciate all the details you provided, that's very helpful.

I just installed the latest package on my arch machine and unfortunately I can't reproduce it. A few questions:
- Which version of Neovim do you have installed? You can check by running `nvim --version` at the command prompt.
- Are you opening oni via the terminal? Are any arguments passed?

It looks like the crash is occurring either here:
https://github.com/onivim/oni/blob/45f51c59b40dab399f96f2476e9040ee75ee725e/browser/src/Services/Completion/Completion.ts#L137

Or here:
https://github.com/onivim/oni/blob/45f51c59b40dab399f96f2476e9040ee75ee725e/browser/src/Services/Completion/Completion.ts#L149

It does seem like there is a bug in the latter logic, in that if we get a buffer update from Neovim _before_  we get a cursor move event, we could hit that crash. I'll take a look at a fix for that. In the meantime, it'd be great to know the results above, to see if there any clues in terms of how we get into this state.

**Comment by muream** [comment] 2017-12-05 22:15
I was opening Oni from the Applications menu, I just tried from the command line (no arguments) and it didn't work either.

Here's what nvim --version gives me:
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

Would it help you if I tried to build oni from source?

**Comment by bryphe** [comment] 2017-12-05 22:55
Thanks @muream ! The neovim version looks perfect - so no issue there.

> Would it help you if I tried to build oni from source?

That would be great. I created a PR #1078 that addresses the crash - I'm curious if it will unblock loading. Let me know if you hit any hurdles trying to build.

**Comment by muream** [comment] 2017-12-06 10:02
Okay, I'll try tomorrow evening! I can't before that.

**Comment by bryphe** [comment] 2017-12-12 03:32
Sounds like it's working now, based on our discussion in gitter. I'll close this out, but let me know if you still hit issues! I hope we can have a better error experience around this - #38 / #39 track getting messages on load, which  would've helped significantly here.

**Closed by bryphe** 2017-12-12 03:32 UTC
Labels: bug, linux
