### ISSUE TITLE
Can I use oni with nvim 3.0 (dev)?

### ISSUE THREAD

**Issue by mrbig033** [onivim/oni#2105] opened 2018-04-17 03:22 UTC
Even though I exported the env. variable as instructed, Oni doesn't seem to find my Nvim install. Would I need to downgrade for it to work?

**Comment by CrossR** [comment] 2018-04-17 08:47
We had a borked version check, which failed for 0.3.0, but was fixed here #2103.
If you aren't running master, then you'd need to download a 0.2.2 appimage. If you are running master, you should be fine!

**Comment by mrbig033** [comment] 2018-04-17 18:26
How can I know if I'm running master or not? I built the following version: 
`NVIM v0.3.0-1029-g48967695c, Build type: RelWithDebInfo`.

**Comment by CrossR** [comment] 2018-04-17 18:33
>How can I know if I'm running master or not?

Sorry, when I say master, I meant the master version of Oni, ie building Oni from source.

Perhaps we should do a release soon though, since I think more and more people are going to have this issue, especially once package managers start to update to using the latest nvim version, even if it isn't officially released yet. 

It may also be worth us popping into the nvim gitter / checking the milestones/roadmap to see when 0.3.0 is expected to release officially...since I think we need to do a release before then.

**Comment by mrbig033** [comment] 2018-04-17 19:13
Okay, no problem :)  I did build it from source and my Oni is 0.3.2. So I guess I need to wait for a newer release. I was excited to try Oni, maybe I'll downgrade for a while just because of it. Thanks!

**Comment by bryphe** [comment] 2018-04-20 02:15
> Perhaps we should do a release soon though, since I think more and more people are going to have this issue, especially once package managers start to update to using the latest nvim version, even if it isn't officially released yet.

Cool, I'm open to doing a release - we certainly want people to be able to use the latest `nvim` with Oni! I'll plan on putting a release out next Friday (4/27). A lot of cool stuff has happened besides the `nvim` fix... VSCode quick open scorer, explorer improvements, new tutorial, new grammars, new themes 😄

**Comment by bryphe** [comment] 2018-05-05 01:48
Release ended up getting a bit delayed because there were a few regressions that were caught - but I'm putting the final touches on 0.3.4 now:  https://github.com/onivim/oni/releases/tag/v0.3.4

That works with Neovim `0.3.0`, and of course our `master` build has the fix too, so I'll close this out. Let me know if you have any issues, though.

**Closed by bryphe** 2018-05-05 01:48 UTC
