### ISSUE TITLE
The App doesn't quit with [command+Q] on macOS

### ISSUE THREAD

**Issue by a-eid** [onivim/oni#928] opened 2017-11-13 05:25 UTC
Most if not all macOS applications terminate with [Command + Q].

**Comment by dasosjt** [comment] 2017-11-13 08:23
Could be configured by a little config file with other bindings/shortcuts

**Comment by freebroccolo** [comment] 2017-11-13 08:26
Strange. I'm on macOS with version `0.2.16` and it does quit on cmd+Q when I try it.

**Comment by bryphe** [comment] 2017-11-13 19:08
Thanks for the report, @a-eid !

Strange, this should have been addressed by PR #787 (there is actually configuration for it here: https://github.com/onivim/oni/blob/01f439771d8fdc3a324cdbf47a7e725c100be0f0/browser/src/Input/KeyBindings.ts#L22)

I wonder if there is a certain case where the input bindings aren't getting captured? That could potentially be a more general issue impacting other scenarios..

@a-eid @dasosjt - does this reproduce consistently for you?

In addition, did you use the latest release binary (0.2.16), or build from source?

**Comment by bryphe** [comment] 2017-12-04 18:55
I'll close this out since I'm unable to reproduce. Feel free to re-open or log a new issue if you're still seeing this!

**Closed by bryphe** 2017-12-04 18:55 UTC
Labels: bug, needs-disambiguation

**Comment by benjamin-rood** [comment] 2017-12-24 23:16
Hi @bryphe I can reproduce this bug. If one closes the Oni window, with `:q` for example, then  <kbd>Command</kbd>+<kbd>Q</kbd> will no longer work.

If the number of Oni windows/tabs is zero, then this should result in also quitting the app.

*Sidenote: I think `q` should behave the same as `bd`, closing rather than closing all the tabs...*
